import { useEffect, useState } from 'react';
import DatePicker from 'react-datepicker';
import { MdEdit } from 'react-icons/md';
import { useParams } from 'react-router-dom';
import UserInfoForm from '../../Components/CheckoutComponents/UserInfoForm';
import { FaArrowRight } from 'react-icons/fa';
import { PiCurrencyInrBold } from 'react-icons/pi';
import Swal from 'sweetalert2';
import 'react-datepicker/dist/react-datepicker.css';
import PaymentInfo from '../../Components/CheckoutComponents/PaymentInfo';
export { useEffect, useState, DatePicker, MdEdit, useParams, UserInfoForm, FaArrowRight, PiCurrencyInrBold, Swal, PaymentInfo };
